### ISSUE TITLE
RichHouseCanvas에서 구현

### ISSUE THREAD

**Issue by vionicbest** [creeper00/Downside_Life#10]
1. 각각의 버튼을 눌렀을 때, 각 층들이 보이게 구현
2. 각 층들에서 물건들을 클릭했을 때, 창이 뜨게 구현
 2.1) 창에서는 도둑질 확률과 도둑질해오는 돈이 나타나야하고, 예, 아니오 버튼이 나타나야함
 2.2) 예 버튼을 눌렀을 때, 확률에 맞춰서 도둑질 해오고, 아니오 버튼을 누르면 층이 나타나야함
3. 다른 메뉴로 가면 다시 메뉴로 돌아오면 부자의 집이 default하게 보이게 설정

**Comment by AlongwithKiman** [comment]
+ 부자 집 각 층 -> 부자 집 전경 으로 돌아가기.

**Comment by AlongwithKiman** [comment]
구현 완료. push한 것 확인 부탁드립니다~~

**Comment by vionicbest** [comment]
확인완료
