### ISSUE TITLE
UnitsCanvas 슬롯

### ISSUE THREAD

**Issue by vionicbest** [creeper00/Downside_Life#11]
아이템을 드래그 앤 드랍해서 슬롯에 있는 캐릭터나 scrollview 에 있는 유닛들에 장착을 할 수 있어야 함. 드래그 해서 그림위에 올릴 때, 유닛이 어떻게 바뀌는지 보여줘야 함
#6 가 선행조건임

**Comment by vionicbest** [comment]
유닛제거 추가해야함

**Comment by coffeetea99** [comment]
유닛 제거 추가됨

**Comment by vionicbest** [comment]
확인완료
