### ISSUE TITLE
한 턴 끝날 때의 변화 구현

### ISSUE THREAD

**Issue by coffeetea99** [creeper00/Downside_Life#41]
공장 수입에 따른 부자 재산 증가
붙인 사기꾼에 따른 부자 재산 감소
붙인 사기꾼에 따른 플레이어 재산 증가
부자 재산 감소에 따른 부자 절박함 증가

또 있으면 아래 comment에 추가바람

**Comment by coffeetea99** [comment]
end turn button에 있는 코드를 따라가면 될 것

**Comment by digdhg** [comment]
꽃뱀의 환급형 아이템 얻는 여부
