### ISSUE TITLE
절박함 관련 이벤트 구현

### ISSUE THREAD

**Issue by digdhg** [creeper00/Downside_Life#60]

**Comment by coffeetea99** [comment]
GameManager.Resource에 절박함 수치가 있고, 그 수치들에 따라서 GameManager.Event에서 다음 이벤트들에 대해 관리한다. 이를 MainScene에 이벤트부분에서 나타낸다

라고 적혀 있었다

**Comment by coffeetea99** [comment]
구현 완료
